version: "3.8"
services:
  build:
    image: buildimage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - build_volume:/opt/build


volumes:
  build_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/build_volume